"use client";

import { useContext } from "react";
import { LanguageContext } from "@/contexts/language-context";

export type Language = "id" | "en";

export const translations = {
  id: {
    // Navigation
    home: "Beranda",
    culinary: "Kuliner",
    clothing: "Pakaian Adat",
    arts: "Kesenian",
    occupations: "Pekerjaan",
    customs: "Adat & Tradisi",
    values: "Nilai-Nilai",

    // Home Page
    welcome: "Selamat Datang di Banyuwangi",
    sunrise: "The Sunrise of Java",
    explore: "Jelajahi Budaya Kami",
    explorePesona: "Jelajahi Pesona Banyuwangi",
    explorePesonaDesc: "Dari kuliner tradisional hingga kesenian yang memukau, temukan keunikan budaya Banyuwangi",
    culinaryTitle: "Cita Rasa Asli",
    culinaryDesc: "Makanan khas Banyuwangi yang menggabungkan cita rasa tradisional dengan inovasi lokal",
    clothingTitle: "Pakaian Adat",
    clothingDesc: "Keanggunan pakaian tradisional Osing yang mencerminkan identitas budaya Banyuwangi",
    artsTitle: "Kesenian Daerah",
    artsDesc: "Tari Gandrung, Seblang, dan kesenian tradisional yang memikat dunia",
    occupationsTitle: "Pekerjaan Masyarakat",
    occupationsDesc: "Keberagaman profesi dan mata pencaharian masyarakat Banyuwangi yang dinamis",
    customsTitle: "Adat & Tradisi",
    customsDesc: "Upacara sakral dan tradisi unik yang tetap hidup dalam kehidupan masyarakat",
    valuesTitle: "Nilai-Nilai Kehidupan",
    valuesDesc: "Gotong royong, spiritualitas, dan cinta lingkungan yang menjadi fondasi budaya",
    learnMore: "Pelajari Lebih Lanjut",
    banyuwangiAwaits: "Banyuwangi Menanti Anda",
    banyuwangiDesc: "Banyuwangi bukan sekadar kota di ujung timur Jawa, tetapi sebuah ruang hidup di mana budaya, alam, dan manusia berpadu dalam harmoni yang indah.",
    startExplore: "Mulai Jelajahi",
    backHome: "Kembali ke Beranda",

    // Culinary Page
    culinaryPageTitle: "Cita Rasa Asli Banyuwangi",
    culinaryPageDesc: "Jelajahi kelezatan kuliner tradisional yang telah diwariskan turun-temurun",
    culinaryHeritage: "Warisan Kuliner Banyuwangi",
    culinaryHeritageDesc: "Kuliner Banyuwangi adalah cerminan dari kekayaan budaya dan sejarah panjang masyarakat Osing. Setiap hidangan menceritakan kisah tentang tradisi, kebersamaan, dan cinta terhadap cita rasa autentik.",
    culinaryHeritageDesc2: "Dari sup tradisional hingga camilan lezat, setiap resep telah disempurnakan selama berabad-abad dan menjadi bagian integral dari identitas kuliner Banyuwangi.",
    specialDishes: "Hidangan Khas Banyuwangi",
    mainIngredients: "Bahan utama:",
    culinaryExperience: "Pengalaman Kuliner",
    authenticTaste: "Cita Rasa Autentik",
    authenticTasteDesc: "Setiap hidangan dibuat dengan resep tradisional yang telah diwariskan dari generasi ke generasi, menggunakan bahan-bahan pilihan berkualitas tinggi.",
    togetherness: "Kebersamaan",
    togetherDesc: "Kuliner Banyuwangi adalah simbol kebersamaan dan gotong royong. Setiap hidangan dimaksudkan untuk dinikmati bersama keluarga dan teman-teman.",
    tasteBanyuwangi: "Rasakan Kelezatan Banyuwangi",
    tasteBanyuwangiDesc: "Kunjungi Banyuwangi dan nikmati pengalaman kuliner yang tak terlupakan. Setiap gigitan adalah perjalanan melalui tradisi dan budaya yang kaya.",

    // Clothing Page
    clothingPageTitle: "Pakaian Adat Osing",
    clothingPageDesc: "Keanggunan dan keindahan dalam setiap jahitan tradisional",
    clothingHeritage: "Warisan Pakaian Tradisional",
    clothingHeritageDesc:
      "Pakaian adat Osing adalah simbol identitas budaya masyarakat Banyuwangi yang telah diwariskan selama berabad-abad. Setiap elemen, dari warna hingga motif, memiliki makna mendalam yang terhubung dengan sejarah, kepercayaan, dan nilai-nilai budaya lokal.",
    clothingHeritageDesc2:
      "Keindahan pakaian adat Osing terletak pada detail yang rumit, penggunaan bahan berkualitas tinggi, dan keahlian pengrajin yang luar biasa. Hingga hari ini, pakaian adat masih digunakan dalam upacara adat, pernikahan, dan perayaan budaya penting.",
    clothingCollection: "Koleksi Pakaian Adat",
    characteristics: "Karakteristik:",
    usedFor: "Digunakan untuk:",
    culturalMeaning: "Makna Budaya",
    culturalIdentity: "Identitas Budaya",
    culturalIdentityDesc: "Pakaian adat adalah representasi visual dari identitas dan kebanggaan budaya masyarakat Osing yang kuat.",
    familyHeritage: "Warisan Keluarga",
    familyHeritageDesc: "Banyak pakaian adat diwariskan dari generasi ke generasi sebagai harta karun keluarga yang berharga.",
    communityBond: "Kebersamaan",
    communityBondDesc: "Mengenakan pakaian adat dalam acara bersama memperkuat ikatan komunitas dan rasa persatuan.",
    preserveCulture: "Lestarikan Warisan Budaya",
    preserveCultureDesc: "Pakaian adat Osing adalah jembatan antara masa lalu dan masa depan. Dengan melestarikan dan mengenakan pakaian tradisional, kita menjaga warisan budaya untuk generasi mendatang.",

    // Arts Page
    artsPageTitle: "Kesenian Daerah Banyuwangi",
    artsPageDesc: "Seni dan budaya yang memukau dunia dengan keindahan dan makna mendalam",
    artsHeritage: "Warisan Seni Banyuwangi",
    artsHeritageDesc: "Kesenian Banyuwangi adalah ekspresi jiwa masyarakat Osing yang telah berkembang selama berabad-abad. Setiap bentuk seni, dari tari hingga musik, membawa cerita, nilai-nilai, dan spiritualitas yang mendalam.",
    artsHeritageDesc2: "Tari Gandrung dan Seblang telah diakui secara internasional sebagai simbol budaya Indonesia yang unik. Seni-seni tradisional ini terus dilestarikan dan dikembangkan oleh generasi muda Banyuwangi.",
    artsCollection: "Koleksi Seni Tradisional",
    history: "Sejarah:",
    culturalImpact: "Dampak Budaya",
    globalRecognition: "Pengakuan Global",
    globalRecognitionDesc: "Seni Banyuwangi telah diakui oleh UNESCO dan ditampilkan di panggung internasional, membawa kebanggaan budaya Indonesia ke seluruh dunia.",
    culturePreservation: "Pelestarian Budaya",
    culturePreservationDesc: "Generasi muda Banyuwangi terus belajar dan melestarikan seni tradisional melalui sekolah seni dan komunitas budaya yang aktif.",
    continuousInnovation: "Inovasi Berkelanjutan",
    continuousInnovationDesc: "Seni tradisional terus berkembang dengan sentuhan modern, menciptakan harmoni antara warisan masa lalu dan kreativitas masa kini.",
    culturalEvents: "Acara Budaya",
    watchArts: "Saksikan Keindahan Seni Banyuwangi",
    watchArtsDesc: "Datang ke Banyuwangi dan rasakan pengalaman seni yang tak terlupakan. Setiap pertunjukan adalah perjalanan spiritual melalui budaya yang kaya dan bermakna.",

    // Occupations Page
    occupationsPageTitle: "Pekerjaan Masyarakat Banyuwangi",
    occupationsPageDesc: "Keberagaman profesi dan mata pencaharian yang dinamis",
    occupationsHeritage: "Warisan Pekerjaan Tradisional",
    occupationsHeritageDesc: "Pekerjaan masyarakat Banyuwangi mencerminkan kekayaan sumber daya alam dan kreativitas lokal. Dari nelayan tangguh hingga pengrajin ulung, setiap profesi berkontribusi pada kehidupan komunitas.",
    occupationsHeritageDesc2: "Meskipun modernisasi membawa perubahan, nilai-nilai tradisional seperti kerja keras, kejujuran, dan gotong royong tetap menjadi fondasi setiap pekerjaan.",
    occupationsCollection: "Beragam Pekerjaan",
    activities: "Kegiatan:",
    significance: "Makna:",
    economicContribution: "Kontribusi Ekonomi",
    primarySector: "Sektor Primer",
    primarySectorDesc: "Pertanian, perikanan, dan kehutanan menjadi tulang punggung ekonomi Banyuwangi dengan kontribusi signifikan terhadap PDB daerah.",
    secondaryTertiarySector: "Sektor Sekunder & Tersier",
    secondaryTertiarySectorDesc: "Industri pengolahan, pariwisata, dan jasa terus berkembang, menciptakan lapangan kerja baru dan meningkatkan kesejahteraan masyarakat.",
    skillsTraining: "Pengembangan Keterampilan",
    traditionalTraining: "Pelatihan Tradisional",
    traditionalTrainingDesc: "Keterampilan tradisional diwariskan dari generasi ke generasi melalui pembelajaran langsung dan pengalaman praktis di lapangan.",
    formalEducation: "Program Pendidikan Formal",
    formalEducationDesc: "Sekolah kejuruan dan lembaga pelatihan menyediakan program pendidikan untuk meningkatkan keterampilan dan kompetensi tenaga kerja lokal.",
    innovationModernization: "Inovasi & Modernisasi",
    innovationModernizationDesc: "Adopsi teknologi modern dan inovasi bisnis membantu meningkatkan produktivitas dan daya saing di pasar global.",
    joinEconomy: "Bergabunglah dengan Ekonomi Banyuwangi",
    joinEconomyDesc: "Banyuwangi menawarkan peluang bisnis dan karir yang menjanjikan. Dengan sumber daya alam yang melimpah dan masyarakat yang berdedikasi, masa depan ekonomi Banyuwangi sangat cerah.",

    // Customs Page
    customsPageTitle: "Adat & Tradisi Banyuwangi",
    customsPageDesc: "Upacara sakral dan tradisi unik yang tetap hidup dalam kehidupan masyarakat",
    customsHeritage: "Warisan Adat & Tradisi",
    customsHeritageDesc: "Adat dan tradisi Banyuwangi adalah fondasi kehidupan sosial dan spiritual masyarakat Osing. Setiap ritual memiliki makna mendalam yang menghubungkan masa lalu dengan masa kini.",
    customsHeritageDesc2: "Dari upacara Seblang hingga pernikahan adat, setiap tradisi memperkuat ikatan komunitas dan menjaga kelestarian budaya.",
    customsCollection: "Koleksi Adat & Tradisi",
    meaning: "Makna:",
    implementationTime: "Waktu Pelaksanaan:",
    coreValues: "Nilai-Nilai Inti",
    togetherness: "Kebersamaan",
    togethernessDesc: "Gotong royong dan saling membantu dalam setiap aspek kehidupan.",
    spirituality: "Spiritualitas",
    spiritualityDesc: "Kepercayaan mendalam terhadap kekuatan spiritual dan leluhur.",
    mutualRespect: "Saling Hormat",
    mutualRespectDesc: "Menghormati sesama manusia dan lingkungan sekitar.",
    harmonyWithNature: "Harmoni dengan Alam",
    harmonyWithNatureDesc: "Keseimbangan antara manusia dan alam sebagai bagian dari kehidupan.",
    traditionPreservation: "Pelestarian Tradisi",
    youthEducation: "Pendidikan Generasi Muda",
    youthEducationDesc: "Orang tua dan pemimpin komunitas secara aktif mengajarkan tradisi kepada generasi muda melalui pembelajaran langsung dan partisipasi dalam upacara-upacara penting.",
    culturalOrganizations: "Organisasi Budaya",
    culturalOrganizationsDesc: "Berbagai organisasi dan komunitas budaya bekerja untuk mendokumentasikan, melestarikan, dan mempromosikan tradisi Osing kepada masyarakat luas.",
    modernAdaptation: "Adaptasi Modern",
    modernAdaptationDesc: "Tradisi terus berkembang dengan adaptasi modern sambil mempertahankan esensi dan makna spiritual yang mendalam dari setiap ritual.",
    respectPreserveTradition: "Hormati & Lestarikan Tradisi",
    respectPreserveTraditionDesc: "Adat dan tradisi Osing adalah warisan berharga yang perlu dilestarikan untuk generasi mendatang. Dengan menghormati dan mempraktikkan tradisi, kita menjaga identitas budaya yang kaya dan bermakna.",

    // Values Page
    valuesPageTitle: "Nilai-Nilai Kehidupan Osing",
    valuesPageDesc: "Prinsip-prinsip yang membimbing kehidupan dan membentuk karakter masyarakat Banyuwangi",
    valuesFoundation: "Fondasi Budaya Osing",
    valuesFoundationDesc: "Nilai-nilai kehidupan Osing adalah hasil dari pengalaman berabad-abad hidup bersama alam, komunitas, dan spiritualitas. Setiap nilai memiliki akar yang dalam dalam sejarah dan kepercayaan masyarakat Banyuwangi.",
    valuesFoundationDesc2: "Nilai-nilai ini bukan hanya filosofi abstrak, tetapi panduan praktis yang diterapkan dalam kehidupan sehari-hari, membentuk karakter, hubungan sosial, dan cara masyarakat berinteraksi dengan alam.",
    valuesCollection: "Nilai-Nilai Utama",
    integrationValues: "Integrasi Nilai dalam Kehidupan",
    learnApplyValues: "Pelajari & Terapkan Nilai-Nilai Osing",
    learnApplyValuesDesc: "Nilai-nilai Osing bukan hanya milik masyarakat Banyuwangi, tetapi dapat menjadi inspirasi bagi siapa saja yang mencari kehidupan yang bermakna, harmonis, dan berkelanjutan.",
  },
  en: {
    // Navigation
    home: "Home",
    culinary: "Culinary",
    clothing: "Traditional Clothing",
    arts: "Arts",
    occupations: "Occupations",
    customs: "Customs & Traditions",
    values: "Values",

    // Home Page
    welcome: "Welcome to Banyuwangi",
    sunrise: "The Sunrise of Java",
    explore: "Explore Our Culture",
    explorePesona: "Explore the Charm of Banyuwangi",
    explorePesonaDesc: "From traditional cuisine to captivating arts, discover the unique culture of Banyuwangi",
    culinaryTitle: "Authentic Flavors",
    culinaryDesc: "Banyuwangi's signature dishes that blend traditional tastes with local innovation",
    clothingTitle: "Traditional Clothing",
    clothingDesc: "The elegance of Osing traditional attire reflecting Banyuwangi's cultural identity",
    artsTitle: "Regional Arts",
    artsDesc: "Gandrung Dance, Seblang, and traditional arts that captivate the world",
    occupationsTitle: "Community Occupations",
    occupationsDesc: "The diversity of professions and livelihoods of dynamic Banyuwangi society",
    customsTitle: "Customs & Traditions",
    customsDesc: "Sacred ceremonies and unique traditions that remain alive in community life",
    valuesTitle: "Life Values",
    valuesDesc: "Mutual cooperation, spirituality, and love for nature that form the foundation of culture",
    learnMore: "Learn More",
    banyuwangiAwaits: "Banyuwangi Awaits You",
    banyuwangiDesc: "Banyuwangi is not just a city at the eastern tip of Java, but a living space where culture, nature, and people blend in beautiful harmony.",
    startExplore: "Start Exploring",
    backHome: "Back to Home",

    // Culinary Page
    culinaryPageTitle: "Authentic Flavors of Banyuwangi",
    culinaryPageDesc: "Explore the delicious traditional cuisine passed down through generations",
    culinaryHeritage: "Banyuwangi's Culinary Heritage",
    culinaryHeritageDesc: "Banyuwangi's cuisine reflects the richness of culture and long history of the Osing people. Each dish tells a story of tradition, togetherness, and love for authentic flavors.",
    culinaryHeritageDesc2: "From traditional soups to delicious snacks, every recipe has been perfected over centuries and become an integral part of Banyuwangi's culinary identity.",
    specialDishes: "Banyuwangi's Special Dishes",
    mainIngredients: "Main ingredients:",
    culinaryExperience: "Culinary Experience",
    authenticTaste: "Authentic Taste",
    authenticTasteDesc: "Each dish is made with traditional recipes passed down from generation to generation, using high-quality selected ingredients.",
    togetherness: "Togetherness",
    togetherDesc: "Banyuwangi's cuisine is a symbol of togetherness and mutual cooperation. Each dish is meant to be enjoyed together with family and friends.",
    tasteBanyuwangi: "Taste the Deliciousness of Banyuwangi",
    tasteBanyuwangiDesc: "Visit Banyuwangi and enjoy an unforgettable culinary experience. Every bite is a journey through rich tradition and culture.",

    // Clothing Page
    clothingPageTitle: "Osing Traditional Clothing",
    clothingPageDesc: "Elegance and beauty in every traditional stitch",
    clothingHeritage: "Heritage of Traditional Clothing",
    clothingHeritageDesc:
      "Osing traditional clothing is a symbol of cultural identity of Banyuwangi people that has been passed down for centuries. Every element, from color to pattern, has deep meaning connected to history, beliefs, and local cultural values.",
    clothingHeritageDesc2:
      "The beauty of Osing traditional clothing lies in intricate details, use of high-quality materials, and extraordinary craftsmanship. Today, traditional clothing is still used in traditional ceremonies, weddings, and important cultural celebrations.",
    clothingCollection: "Traditional Clothing Collection",
    characteristics: "Characteristics:",
    usedFor: "Used for:",
    culturalMeaning: "Cultural Meaning",
    culturalIdentity: "Cultural Identity",
    culturalIdentityDesc: "Traditional clothing is a visual representation of the identity and pride of Osing people's strong culture.",
    familyHeritage: "Family Heritage",
    familyHeritageDesc: "Many traditional clothes are passed down from generation to generation as precious family treasures.",
    communityBond: "Community Bond",
    communityBondDesc: "Wearing traditional clothing in community events strengthens community bonds and sense of unity.",
    preserveCulture: "Preserve Cultural Heritage",
    preserveCultureDesc: "Osing traditional clothing is a bridge between past and future. By preserving and wearing traditional clothing, we maintain cultural heritage for future generations.",

    // Arts Page
    artsPageTitle: "Banyuwangi Regional Arts",
    artsPageDesc: "Arts and culture that captivate the world with beauty and deep meaning",
    artsHeritage: "Banyuwangi's Arts Heritage",
    artsHeritageDesc: "Banyuwangi's arts are an expression of the Osing people's soul that has developed over centuries. Every form of art, from dance to music, carries stories, values, and deep spirituality.",
    artsHeritageDesc2: "Gandrung and Seblang dances have been internationally recognized as unique symbols of Indonesian culture. These traditional arts continue to be preserved and developed by young people of Banyuwangi.",
    artsCollection: "Traditional Arts Collection",
    history: "History:",
    culturalImpact: "Cultural Impact",
    globalRecognition: "Global Recognition",
    globalRecognitionDesc: "Banyuwangi's arts have been recognized by UNESCO and displayed on international stages, bringing Indonesian cultural pride to the world.",
    culturePreservation: "Culture Preservation",
    culturePreservationDesc: "Young people of Banyuwangi continue to learn and preserve traditional arts through art schools and active cultural communities.",
    continuousInnovation: "Continuous Innovation",
    continuousInnovationDesc: "Traditional arts continue to develop with modern touches, creating harmony between past heritage and contemporary creativity.",
    culturalEvents: "Cultural Events",
    watchArts: "Witness the Beauty of Banyuwangi Arts",
    watchArtsDesc: "Come to Banyuwangi and experience unforgettable art. Every performance is a spiritual journey through rich and meaningful culture.",

    // Occupations Page
    occupationsPageTitle: "Banyuwangi Community Occupations",
    occupationsPageDesc: "Diversity of professions and dynamic livelihoods",
    occupationsHeritage: "Heritage of Traditional Occupations",
    occupationsHeritageDesc: "Banyuwangi community's occupations reflect the richness of natural resources and local creativity. From resilient fishermen to skilled craftsmen, every profession contributes to community life.",
    occupationsHeritageDesc2: "Although modernization brings changes, traditional values such as hard work, honesty, and mutual cooperation remain the foundation of every job.",
    occupationsCollection: "Diverse Occupations",
    activities: "Activities:",
    significance: "Significance:",
    economicContribution: "Economic Contribution",
    primarySector: "Primary Sector",
    primarySectorDesc: "Agriculture, fisheries, and forestry become the backbone of Banyuwangi's economy with significant contributions to regional GDP.",
    secondaryTertiarySector: "Secondary & Tertiary Sector",
    secondaryTertiarySectorDesc: "Processing industries, tourism, and services continue to develop, creating new jobs and improving community welfare.",
    skillsTraining: "Skills Development",
    traditionalTraining: "Traditional Training",
    traditionalTrainingDesc: "Traditional skills are passed down from generation to generation through direct learning and practical experience in the field.",
    formalEducation: "Formal Education Programs",
    formalEducationDesc: "Vocational schools and training institutions provide education programs to improve skills and competencies of local workforce.",
    innovationModernization: "Innovation & Modernization",
    innovationModernizationDesc: "Adoption of modern technology and business innovation helps increase productivity and competitiveness in the global market.",
    joinEconomy: "Join Banyuwangi's Economy",
    joinEconomyDesc: "Banyuwangi offers promising business and career opportunities. With abundant natural resources and dedicated community, Banyuwangi's economic future is very bright.",

    // Customs Page
    customsPageTitle: "Banyuwangi Customs & Traditions",
    customsPageDesc: "Sacred ceremonies and unique traditions that remain alive in community life",
    customsHeritage: "Heritage of Customs & Traditions",
    customsHeritageDesc: "Banyuwangi's customs and traditions are the foundation of social and spiritual life of the Osing people. Every ritual has deep meaning that connects the past with the present.",
    customsHeritageDesc2: "From Seblang ceremonies to traditional weddings, every tradition strengthens community bonds and preserves cultural sustainability.",
    customsCollection: "Customs & Traditions Collection",
    meaning: "Meaning:",
    implementationTime: "Implementation Time:",
    coreValues: "Core Values",
    togetherness: "Togetherness",
    togethernessDesc: "Mutual cooperation and helping each other in every aspect of life.",
    spirituality: "Spirituality",
    spiritualityDesc: "Deep belief in spiritual powers and ancestors.",
    mutualRespect: "Mutual Respect",
    mutualRespectDesc: "Respecting fellow humans and the surrounding environment.",
    harmonyWithNature: "Harmony with Nature",
    harmonyWithNatureDesc: "Balance between humans and nature as part of life.",
    traditionPreservation: "Tradition Preservation",
    youthEducation: "Youth Education",
    youthEducationDesc: "Parents and community leaders actively teach traditions to young generations through direct learning and participation in important ceremonies.",
    culturalOrganizations: "Cultural Organizations",
    culturalOrganizationsDesc: "Various cultural organizations and communities work to document, preserve, and promote Osing traditions to the wider community.",
    modernAdaptation: "Modern Adaptation",
    modernAdaptationDesc: "Traditions continue to develop with modern adaptations while maintaining the essence and deep spiritual meaning of each ritual.",
    respectPreserveTradition: "Respect & Preserve Tradition",
    respectPreserveTraditionDesc: "Osing customs and traditions are valuable heritage that need to be preserved for future generations. By respecting and practicing traditions, we maintain rich and meaningful cultural identity.",

    // Values Page
    valuesPageTitle: "Osing Life Values",
    valuesPageDesc: "Principles that guide life and shape the character of Banyuwangi society",
    valuesFoundation: "Osing Cultural Foundation",
    valuesFoundationDesc: "Osing life values are the result of centuries of experience living together with nature, community, and spirituality. Each value has deep roots in the history and beliefs of Banyuwangi people.",
    valuesFoundationDesc2: "These values are not just abstract philosophy, but practical guidelines applied in daily life, shaping character, social relationships, and how people interact with nature.",
    valuesCollection: "Main Values",
    integrationValues: "Integration of Values in Life",
    learnApplyValues: "Learn & Apply Osing Values",
    learnApplyValuesDesc: "Osing values are not only owned by Banyuwangi people, but can inspire anyone seeking a meaningful, harmonious, and sustainable life.",
  },
};

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
